### ISSUE TITLE
BC issue

### ISSUE THREAD

**Issue by marek-l** [PHPExpertsEU/DateTimeImmutableFormBundle#1]
After upgrade for Symfony3 lib can not be used in projects where is symfony2/php5.6. Pls create branch for this case.

**Comment by zsolt-racz** [comment]
Thanks for reporting. I've created new tags in order to support multiple Symfony versions. Please use "~2.0.0" in your composer.json for Symfony 2.1+ compatibility, or "~3.0.0" for 3.0+ compatibility.

Please let me know if it worked for you.

**Comment by marek-l** [comment]
Thanks a lot, under symfony 2.8 works well.
